### ISSUE TITLE
Github Actions 运行报了一个错，能指导一下吗？

### ISSUE THREAD

**Issue by kurtn2005** [xunichanghuan/mimotion#4]
请问报了这个错误是什么意思呢？谢谢。

Traceback (most recent call last):
  File "main.py", line 349, in <module>
    getBeijinTime()
  File "main.py", line 93, in getBeijinTime
    getWeather()
  File "main.py", line 64, in getWeather
    if "多云" in res['data']['forecast'][0]['type']:
KeyError: 'data'
Error: Process completed with exit code 1.

**Comment by xunichanghuan** [comment]
搞定了没

**Comment by kurtn2005** [comment]
> 搞定了没

检查了发现area赋值带了引号，去掉引号就好了。我猜是这个问题。
