### ISSUE TITLE
action执行失败，httpconnection time out

### ISSUE THREAD

**Issue by lutcraft** [xunichanghuan/mimotion#61]
Run pip3 install requests
  
Collecting requests
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 6.2 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 10.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 17.8 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.[21](https://github.com/lutcraft/mimotion/actions/runs/3449172298/jobs/5756856127#step:5:21).1
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 39.6 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-20[22](https://github.com/lutcraft/mimotion/actions/runs/3449172298/jobs/5756856127#step:5:23).9.24 charset-normalizer-2.1.1 idna-3.4 requests-2.28.1 urllib3-1.26.12

Notice:  A new release of pip available: 22.3 -> 22.3.1
Notice:  To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connection.py", line [23](https://github.com/lutcraft/mimotion/actions/runs/3449172298/jobs/5756856127#step:5:24)9, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/http/client.py", line 1[25](https://github.com/lutcraft/mimotion/actions/runs/3449172298/jobs/5756856127#step:5:26)6, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/http/client.py", line 1[30](https://github.com/lutcraft/mimotion/actions/runs/3449172298/jobs/5756856127#step:5:31)2, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f769dc381c0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='time1909.beijing-time.org', port=80): Max retries exceeded with url: /time.asp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f769dc381c0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line [35](https://github.com/lutcraft/mimotion/actions/runs/3449172298/jobs/5756856127#step:5:36)6, in <module>
    getBeijinTime()
  File "main.py", line 101, in getBeijinTime
    r = requests.get(url=url, headers=hea)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='time1909.beijing-time.org', port=80): Max retries exceeded with url: /time.asp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f769dc[38](https://github.com/lutcraft/mimotion/actions/runs/3449172298/jobs/5756856127#step:5:39)1c0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Error: Process completed with exit code 1.

**Comment by yatotm** [comment]
time1909.beijing-time.org
这个获取时间的网站打不开了，替换一个别的

**Comment by yatotm** [comment]
> 
编辑main.py 把原本的获取在线时间的地址改了
比如改成这个
https://www.beijing-time.org/t/time.asp

**Comment by 0yykk** [comment]
> > 
> 
> 编辑main.py 把原本的获取在线时间的地址改了 比如改成这个 https://www.beijing-time.org/t/time.asp

可行
