### ISSUE TITLE
刷步数成功，但是每次都有一个错误

### ISSUE THREAD

**Issue by qiuhaiwei2020** [xunichanghuan/mimotion#9]
显示：File "main.py", line 315, in get_access_token
    access_token = resp['access_token']
KeyError: 'access_token'
Error: Process completed with exit code 1.

**Comment by delete222** [comment]
遇到了同样的问题

**Comment by zailushang2008** [comment]
我也遇到了同样的问题，还有没有开启天气，为啥下方还是有天气的错误呀？设置的False和NO
已设置为随机步数(2354~2456)
[2021-08-23 07:55:13]
账号：***
由于天气 修改步数（2445）
Traceback (most recent call last):
  File "main.py", line 352, in <module>
    getBeijinTime()
  File "main.py", line 151, in getBeijinTime
    main(user_mi,passwd_mi,min_1, max_1, a)     
  File "main.py", line 259, in main
    run(result)
  File "main.py", line 336, in run
    req_urls = req_url + get_access_token()
  File "main.py", line 315, in get_access_token
    access_token = resp['access_token']
KeyError: 'access_token'
success
{"code":0,"message":"","data":{"pushid":"","readkey":"","error":"SUCCESS","errno":0}}
Error: Process completed with exit code 1.

**Comment by xunichanghuan** [comment]
已修复,请重新Fork。请点Star支持一下。
